export type ProductType = {
  id: string;
  productType: number;
  staff: string;
  supplierId: string;
  supplierName: string;
  grayFabricId: string;
  productNumber: string;
  productNum: string;
  productName: string;
  colorNum: string;
  colorName: string;
  price: number;
  materialName: string;
  materials: any;
  fabricWidth: number;
  fabricWeight: number;
  fabricLength: number;
  features: [];
  noteProduct: string;
  noteFabric: string;
  noteEtc: string;
  wip: number;
  externalStock: number;
  arrivingQuantity: number;
  tokushimaStock: number;
};
